# Generated by Django 6.0.2 on 2026-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('terms', 'Пользовательское соглашение'), ('privacy', 'Политика конфиденциальности'), ('offer', 'Оферта'), ('requisites', 'Реквизиты'), ('return', 'Возврат и обмен')], unique=True, verbose_name='Идентификатор (slug)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое (HTML)')),
            ],
            options={
                'verbose_name': 'юридическая страница',
                'verbose_name_plural': 'юридические страницы',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main', editable=False, max_length=50, unique=True, verbose_name='Ключ')),
                ('site_name', models.CharField(default='Магазин', max_length=255, verbose_name='Название сайта')),
                ('site_description', models.CharField(blank=True, default='Интернет-магазин', max_length=255, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
    ]
