# Generated by Django 6.0.2 on 2026-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_legal_pages_and_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='slug',
            field=models.SlugField(choices=[('terms', 'Пользовательское соглашение'), ('privacy', 'Политика конфиденциальности'), ('offer', 'Оферта'), ('requisites', 'Реквизиты'), ('return', 'Возврат и обмен'), ('payment_delivery', 'Оплата и доставка'), ('contacts', 'Контакты')], unique=True, verbose_name='Идентификатор (slug)'),
        ),
    ]
