# Generated by Django 6.0.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
