# Generated by Django 6.0.2 on 2026-03-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Внутренний артикул товара', max_length=50, verbose_name='Артикул'),
        ),
    ]
