# Generated by Django 6.0.2

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def create_variants_and_assign_images(apps, schema_editor):
    """Для каждого Product создаём один ProductVariant, переносим цену/sku; привязываем фото."""
    Product = apps.get_model("catalog", "Product")
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    ProductImage = apps.get_model("catalog", "ProductImage")

    for product in Product.objects.all():
        variant = ProductVariant.objects.create(
            product=product,
            color="",
            sku=product.sku or "",
            price=product.price or Decimal("0"),
            discount_percent=product.discount_percent or Decimal("0"),
            order=0,
            is_active=True,
        )
        ProductImage.objects.filter(product=product).update(variant=variant)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="ЧПУ для URL; если пусто — используется id",
                max_length=300,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Например: красный, синий",
                        max_length=100,
                        verbose_name="Цвет / исполнение",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Внутренний артикул варианта",
                        max_length=50,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена в рублях",
                        max_digits=12,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Процент скидки (0 — без скидки)",
                        max_digits=5,
                        verbose_name="Размер скидки, %",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант товара",
                "verbose_name_plural": "Варианты товара",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="productimage",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.productvariant",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.RunPython(create_variants_and_assign_images, noop_reverse),
    ]
