# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


def set_variant_from_product(apps, schema_editor):
    """Для каждой позиции корзины задаём variant = первый вариант товара product."""
    CartItem = apps.get_model("cart", "CartItem")
    ProductVariant = apps.get_model("catalog", "ProductVariant")

    for item in CartItem.objects.select_related("product").all():
        variant = ProductVariant.objects.filter(product=item.product).first()
        if variant:
            item.variant = variant
            item.save(update_fields=["variant"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_product_price_sku_discount"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="catalog.productvariant",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.RunPython(set_variant_from_product, noop_reverse),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="catalog.productvariant",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "variant")},
        ),
    ]
