# Generated by Django 6.0.2 on 2026-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Пункт выдачи СДЭК'), ('courier', 'Курьер СДЭК')], default='pickup', max_length=20, verbose_name='Тип доставки СДЭК'),
        ),
    ]
