# Generated by Django 6.0.2 on 2026-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_tariff_code',
            field=models.PositiveIntegerField(blank=True, help_text='Код тарифа на момент оформления (136, 137, 138, 233 и т.д.)', null=True, verbose_name='Код тарифа СДЭК'),
        ),
    ]
