# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


def set_variant_from_product(apps, schema_editor):
    """Для каждой позиции заказа задаём variant = первый вариант товара product."""
    OrderItem = apps.get_model("orders", "OrderItem")
    ProductVariant = apps.get_model("catalog", "ProductVariant")

    for item in OrderItem.objects.select_related("product").all():
        variant = ProductVariant.objects.filter(product=item.product).first()
        if variant:
            item.variant = variant
            item.save(update_fields=["variant"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_product_price_sku_discount"),
        ("orders", "0005_add_tbank_payment_id_and_refunded_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.productvariant",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.RunPython(set_variant_from_product, noop_reverse),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.productvariant",
                verbose_name="Вариант товара",
            ),
        ),
    ]
