# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email_paid_sent",
            field=models.BooleanField(default=False, verbose_name="Письмо об оплате отправлено"),
        ),
        migrations.AddField(
            model_name="order",
            name="email_in_delivery_sent",
            field=models.BooleanField(
                default=False,
                verbose_name="Письмо о передаче в доставку отправлено",
            ),
        ),
    ]
